#ifndef INFINITY_ERGODOX_CONFIG_H
#define INFINITY_ERGODOX_CONFIG_H

#define DEBOUNCE 1
#define NO_DEBUG
#define NO_PRINT
#define NO_ACTION_LAYER
#define NO_ACTION_ONESHOT
#define TAPPING_TERM 325
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
// #define RETRO_TAPPING


#endif
